name = "abbiss-api"
main = "src/index.ts"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "abbiss"
database_id = "local"
migrations_dir = "migrations"

[dev]
port = 8787
